### ISSUE TITLE
Visible tearing when scrolling around a map.

### ISSUE THREAD

**Issue by zaun** [kmamal/node-sdl#10]
I'm making a 2D tile-map based game. So far things are working out very well, except there is visible tearing when scrolling around. I should note, I'm not using openGL, I'm using node-canvas and window.render to update the display once every frame.

Is it possible to turn on VSYNC? 

I think thing would have to change to using the renderer and SDL_RenderCopy rather than SDL_BlitSurface in the window_render function.

**Comment by kmamal** [comment]
Good point, I'll see what I can do.

**Comment by kmamal** [comment]
@zaun I have tried to fix this problem in `v0.4.0` where hardware acceleration and vsync are enabled by default. Let me know if it works.
