### ISSUE TITLE
Building from source

### ISSUE THREAD

**Issue by zaun** [kmamal/node-sdl#12]
Write up the “Building from source” section of the readme. I’d like to mess around with adding some additional functionality, but I need to know how to update the native side in addition to the JavaScript side. Right now I can change the JavaScript side but I can’t figure out how to rebuild when changing the native side.

thanks 🙏

**Comment by zaun** [comment]
I had to install ADP from source, using the dmg framework download doesn’t work properly.

**Comment by kmamal** [comment]
Thanks, I will add instructions to build from source to the docs. Beware that it could take some time before it's done as I'd need access to clean installs of each platform, which I won't have for another week at least. Maybe I could spin up some VMs.

**Comment by kmamal** [comment]
@zaun I have added a "Building from source" section in the docs.
