### ISSUE TITLE
window.x and window.y return extremely large incorrect numbers?

### ISSUE THREAD

**Issue by marcus13345** [kmamal/node-sdl#2]
simple test case:
```javascript
const sdl = require('@kmamal/sdl');

const window = sdl.video.createWindow({
	width: 800,
	height: 600
});

const x = window.x;
const y = window.y;
console.log(x, y);

(function loop() {
	let event;
	while(event = sdl.events.poll())
		if (event.type === 'quit') window.destroy();
	if(!window._destroyed) setTimeout(loop, 100);
})()
```

Im getting `805240832` every time I run it, for both x and y.
it appears that this is somewhat defined behavior, as `805240832` seems to be a constant to define window alignment to the screen.

This may be a wont fix, on account of it being true to the binding, however, for my use case, I do need some way of calculating what the _real_ x and y are. If theres a better way, please let me know!

**Comment by kmamal** [comment]
Should be fixed in `v0.0.18`
