### ISSUE TITLE
Could you give an example that how to load a random png/jpg file from local?

### ISSUE THREAD

**Issue by Killea** [kmamal/node-sdl#24]
I always get an error：
`Error: buffer is smaller than expected`

**Comment by kmamal** [comment]
@Killea Here's an example of loading a .png file: https://github.com/kmamal/node-sdl/tree/master/examples/07-ffmpeg-video

If you can't get it o work, please share your code so I can have a look.

**Comment by kmamal** [comment]
Closing this as solved, let me know if you have problems and I'll reopen it.
