### ISSUE TITLE
Destroy window will exit the process?

### ISSUE THREAD

**Issue by LmanTW** [kmamal/node-sdl#25]
I found that destroying the window seems to make the process exit. Is there a way to prevent it from exiting?

**Comment by kmamal** [comment]
Yes, you can call `sdl.on('beforeQuit', (event) => { event.prevent() })`

https://github.com/kmamal/node-sdl#event-beforequit

**Comment by kmamal** [comment]
Closing this as solved, let me know if you have problems and I'll reopen it.

**Comment by kmamal** [comment]
@LmanTW I have found a better way to handle the process lifetime so now after `v0.7.0` destroying a window won't cause the process to exit if you have other stuff going on.
