### ISSUE TITLE
Syntax error in the code

### ISSUE THREAD

**Issue by notcl4y14** [kmamal/node-sdl#27]
![image](https://user-images.githubusercontent.com/128468209/226563027-ae9480c4-9905-4b15-ba5d-1c3fb4f3aabc.png)

**Comment by kmamal** [comment]
@notcl4y14 I think you might be using a Node.js version that is too old and does not support top-level-await (see https://github.com/nodejs/release#release-schedule). You can find out what your Node.js version is by running `node --version`. As you can see in the release schedule, versions before 14 are considered End-of-Life and are not being maintained so I don't try to support them. Please make sure to use one of 14, 16, 18, 19, or 20.

**Comment by notcl4y14** [comment]
Gotcha, thanks

P.S. I'm using node.js 13
