### ISSUE TITLE
Missing X11 Window Flags

### ISSUE THREAD

**Issue by Blade67** [kmamal/node-sdl#29]
I noticed some missing [window flags](https://wiki.libsdl.org/SDL2/SDL_WindowFlags) such as `SDL_WINDOW_VULKAN` which is presumably due to not supporting Vulkan (yet?) but the following are X11 and should probably be supported:
```
SDL_WINDOW_ALWAYS_ON_TOP
SDL_WINDOW_SKIP_TASKBAR
SDL_WINDOW_UTILITY
SDL_WINDOW_TOOLTIP
SDL_WINDOW_POPUP_MENU
```

Additionally, there doesn't seem to be a helper function (ie. `Window.getFlags()`) to easily get the flags as an object.
I would love seeing those added. Thanks for the great work so far!

**Comment by kmamal** [comment]
@Blade67 Thanks for the request. In `v0.7.1` I have added the `alwaysOnTop`, `skipTaskbar`, `popupMenu`, `tooltip`, and `utility` flags to `createWindow()`. For getting the various flags, use the [corresponding properties of the window object](https://github.com/kmamal/node-sdl#windowalwaysontop).

I'm not sure how vulkan can be supported from javascript. My plan was to just use WebGPU. I have made some progress [over here](https://github.com/kmamal/node-sdl/issues/20).
