### ISSUE TITLE
how to change the audio driver dynamically？

### ISSUE THREAD

**Issue by kai230518** [kmamal/node-sdl#30]
Hi,I want to change the audio driver such as directsound,wasapi and waveout,even if the audio is playing.
The `sdl.info` seems to be unable to be modified after initialization.so,how should i do it？

I am a novice programmer and my english is not good,please forgive me.

**Comment by kmamal** [comment]
@kai230518 I'm afraid this is not possible at the moment. I have not implmented this feature yet, and it looks like SDL3 mght not support it at all. I want to wait and see which direction SDL3 takes before implementing this. Maybe if you explain what you are trying to do I can help you find a workaround?

**Comment by kmamal** [comment]
To be more specific: here's the part from the SDL3 migration guide where they say that the [SDL_VideoInit](https://github.com/libsdl-org/SDL/blob/a3ce0d03e36786e762d6541b5754d6a771962e67/docs/README-migration.md?plain=1#L56) and [SDL_AudioInit](https://github.com/libsdl-org/SDL/blob/a3ce0d03e36786e762d6541b5754d6a771962e67/docs/README-migration.md?plain=1#L56) functions are no longer available. These two functions were the only way I was aware of of changing the drivers while the program is still running.

Even if this functionality remains available in some other way, it would not be possible to keep the audio running while the switch is happening. Switching audio driver would necessitate closing all currently playing audio instances.

**Comment by kai230518** [comment]
Thanks!
I am trying to develop a local player through Electron that can play music in different formats, such as M4A, WAV and even DSF.
Additionally, I hope it can also use different system audio APIs to output audio, and open the Exclusive-Mode Streams in Windows.
Because I haven't studied C language before. So, I am struggling with how to achieve it.

**Comment by kai230518** [comment]
> To be more specific: here's the part from the SDL3 migration guide where they say that the [SDL_VideoInit](https://github.com/libsdl-org/SDL/blob/a3ce0d03e36786e762d6541b5754d6a771962e67/docs/README-migration.md?plain=1#L1060) and [SDL_AudioInit](https://github.com/libsdl-org/SDL/blob/a3ce0d03e36786e762d6541b5754d6a771962e67/docs/README-migration.md?plain=1#L56) functions are no longer available. These two functions were the only way I was aware of of changing the drivers while the program is still running.
> 
> Even if this functionality remains available in some other way, it would not be possible to keep the audio running while the switch is happening. Switching audio driver would necessitate closing all currently playing audio instances.

Interruption that occur during the audio driver switching process is acceptable, I can try some methods to continue playing the audio at the interruption point.so, I just want users to be able to choose the audio driver they want.

**Comment by kmamal** [comment]
@kai230518 I have added an example showing how you can switch audio drivers dynamically, by keeping audio playback on a separate process from the main window, and restarting the audio process to change drivers. This is the only way I can imagine it working right now: https://github.com/kmamal/node-sdl/tree/master/examples/13-audio-driver. Using this example on linux I am able to switch between pulseaudio, alsa, and pipewire without havinng to close the windowm or losing playback position.

**Comment by kai230518** [comment]
Thanks!!!!
@kmamal It is a huge help for me, I will make a good use of it.

I noticed that [there](https://github.com/libsdl-org/SDL/blob/1a3b7135240d0f2ff3add4c543524405c005087d/src/audio/wasapi/SDL_wasapi.c#LL377C1-L377C1) is a mention of the  Exclusive-Mode Streams in wasapi, and I want to know if there is any way to use it?

**Comment by kmamal** [comment]
From what they say in that comment, they have not implemented it yet because it causes all other sounds on the system to stop, so there's no way to use it from `@kmamal/sdl`.

**Comment by kai230518** [comment]
> @kai230518 From what they say in that comment, they have not implemented it yet because it causes all other sounds on the system to stop, so there's no way to use it from `@kmamal/sdl`.

OK,I get it and I really appreciate your help.
