### ISSUE TITLE
Support Linux arm64 platform (Raspberry Pi 4)

### ISSUE THREAD

**Issue by dqbd** [kmamal/node-sdl#31]
Hi, thanks for the package!

When attempting to install the package on Raspberry Pi 4 (x64), the installation nor building does seem to work.

Installing package via yarn
```
pi@raspberrypi:~/js $ yarn add @kmamal/sdl
yarn add v1.22.19
info No lockfile found.
[1/4] Resolving packages...
[2/4] Fetching packages...
[3/4] Linking dependencies...
[4/4] Building fresh packages...
error /home/pi/js/node_modules/@kmamal/sdl: Command failed.
Exit code: 1
Command: cd scripts && node install.mjs
Arguments: 
Directory: /home/pi/js/node_modules/@kmamal/sdl
Output:
fetch https://github.com/kmamal/node-sdl/releases/download/v0.7.3/sdl.node-v0.7.3-linux-arm64.tar.gz
failed to download release
fetch https://github.com/kmamal/build-sdl/releases/download/v2.26.4/SDL-v2.26.4-linux-arm64.tar.gz
/home/pi/js/node_modules/@kmamal/sdl/scripts/util/fetch.js:59
                        throw Object.assign(new Error(`bad status code ${statusCode}`), {
                                            ^

Error: bad status code 404
    at fetch (/home/pi/js/node_modules/@kmamal/sdl/scripts/util/fetch.js:59:24)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async file:///home/pi/js/node_modules/@kmamal/sdl/scripts/download-sdl.mjs:10:18 {
  statusCode: 404,
  responseBody: 'Not Found'
}

Node.js v19.8.1
```

Cloning the repository and downloading SDL headers
```
pi@raspberrypi:~/node-sdl $ npm run download-sdl

> @kmamal/sdl@0.7.3 download-sdl
> cd scripts && node download-sdl.mjs

fetch https://github.com/kmamal/build-sdl/releases/download/v2.26.4/SDL-v2.26.4-linux-arm64.tar.gz
/home/pi/node-sdl/scripts/util/fetch.js:59
                        throw Object.assign(new Error(`bad status code ${statusCode}`), {
                                            ^

Error: bad status code 404
    at fetch (/home/pi/node-sdl/scripts/util/fetch.js:59:24)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async file:///home/pi/node-sdl/scripts/download-sdl.mjs:10:18 {
  statusCode: 404,
  responseBody: 'Not Found'
}

Node.js v19.8.1
```

**Comment by kmamal** [comment]
@dqbd Thanks for reporting. This is a bug. The install should not have failed even if there are no prebuilt binaries for your platform available. I'll investigate why that happened.

**Comment by kmamal** [comment]
@dqbd I have released `v0.7.4` and now I hope when it fails to find the binaries it will actually try to build sdl and this package from source. Can you try it and let me know if it works? Be aware that building SDL will probably use a lot of CPU and RAM. I will also make a future release with prebuild linux-arm64 binaries, but I need some time to figure out how cross-compilation for the Pi works.

**Comment by dqbd** [comment]
Thanks for the release! Now running `yarn install @kmamal/sdl` will attempt to build the package. However, building such package is prohibitively expensive when running `cmake` with `--parallel`, making the system unresponsive (tested on the 4GB model).

Will try to run `build-sdl/scripts/make.mjs` overnight to see if I can actually build it without the `--parallel` flag.

**Comment by kmamal** [comment]
@dqbd I have uploaded prebuilt binaries for `build-sdl`. Installing `@kmamal/sdl` should be much faster now. Can you try it and let me know how it goes? I also plan to upload prebuilt binaries for `@kmamal/sdl` later.

**Comment by kmamal** [comment]
@dqbd I have now also added the linux-arm64 prebuilt banaries for `@kmamal/sdl`. Installs on the raspberry pi should be as fast as they can go now. I'll be closing this issue but please get back to me if it doesn't work for you.
