### ISSUE TITLE
Help with window.setIcon()

### ISSUE THREAD

**Issue by QwertyR0** [kmamal/node-sdl#35]
Hello again, i just couldn't get `window.setIcon()` running. I get:
`
Error: buffer is smaller than expected
`
or sometimes:
`
Error: SDL_CreateRGBSurfaceWithFormatFrom(1, 16, 16, 372645892) error: Parameter 'pitch' is invalid
` error.
I tried the same FFmpeg image loading that you provided in the examples.
I don't really know what to do. I would be really grateful if you helped. 

My code:

`
    const icon = await loadImage(game.icon, { width: iconDimensions.width, height: iconDimensions.height });
    window.setIcon(iconDimensions.height, iconDimensions.width, iconDimensions.width*4, 'bgra32', icon);
`

**Comment by kmamal** [comment]
`window.setIcon(iconDimensions.height, iconDimensions.width, iconDimensions.width*4, 'bgra32', icon);`

Width goes first like this:

`window.setIcon(iconDimensions.width, iconDimensions.height, iconDimensions.width*4, 'bgra32', icon);`

**Comment by QwertyR0** [comment]
> 

i still get the same `Error: buffer is smaller than expected`
the image is also a 16x16 so changing it didn't really affect anything

**Comment by kmamal** [comment]
What is printed from `console.log(icon)` after you load the icon? Can you share the icon so I can try too?

**Comment by QwertyR0** [comment]
It is just a buffer:

`
<Buffer 00 00 00 00 00 00 00 00 00 00 00 00 df 71 26 df 71 26 df 71 26 df 71 26 df 71 26 df 71 26 df 71 26 df 71 26 00 00 00 00 00 00 00 00 00 00 00 00 00 00 ... 718 more bytes>
`

**Comment by kmamal** [comment]
That buffer is 768 bytes long. Dividing by  16 * 16 gives 3, so the format is only red green and blue, without an alpha channel. Try replacing `bgra32` with something like `rgb24`.

**Comment by QwertyR0** [comment]
Wow thank you so much.  I never thought of that.
