### ISSUE TITLE
help with joystickInstance.rumble

### ISSUE THREAD

**Issue by QwertyR0** [kmamal/node-sdl#36]
Hello, i was trying to get my joystick to rumble but it doesn't work. The gamepad has rumbling joystick.hasRumble is true
could you give an example on how it works or it is just about mine joystick. Thank you.

**Comment by kmamal** [comment]
I have two gameapds at home, both have `hasRumble: true` but only one of them actually rumbles when I call `rumble()`. So there are 2 cases: either the incorrectly reports that it is able to rumble or `rumble()` is broken.

Is your controller able to rumble in other games?

**Comment by QwertyR0** [comment]
> I have two gameapds at home, both have `hasRumble: true` but only one of them actually rumbles when I call `rumble()`. So there are 2 cases: either the controller incorrectly reports that it is able to rumble, or `rumble()` is broken in SDL.
> 
> Is your controller able to rumble in other games?

My controller does rumble in other games. My friend have also tried with is controller but it didn't work either.

**Comment by lieve-blendi** [comment]
I tested around a bit, and, for me, the rumble works on my (third-party) switch pro controller, but not on my xbox controller.

**Comment by QwertyR0** [comment]
I decided to use another joystick handler and close this issue.

**Comment by kmamal** [comment]
I did some more testing with my devices. It turns out that my non-working gamepad simply does not have rumble and the driver just reports it incorrectly.

I have made a new release (`v0.7.6`) with more error checking around the joystick functions. If you have time, you could help me by downloading it and checking if any errors are thrown when you try to make your controller rumble.

@QwertyR0 what did you switch to? I'd like to see what they are doing differently.

Since this is still a problem for others, I'll reopen this issue so it can be found easier.

**Comment by QwertyR0** [comment]
My joystick can actually be considered as a knockoff (I guess). It has 3 modes and one of which is the `'Xbox 360 Controller'` mode. This is the controller's default mode and only this mode has `hasRumble: true`, so I was testing with this.

Originally I used the `joystickInstance` but i have also tried the `controller`. Both gives out the same: 
`Controller isn't correlated yet, try hitting a button first` error.
I used `setTimeout()` and clicked a button, then `rumble()` worked in both.
If there is any way that I can skip this "correlating" part i would like to know.
I may wait for the user to randomly hit a button, if that is the case.

I was searching for a joystick handler and I ran across, [https://github.com/creationix/node-gamepad](https://github.com/creationix/node-gamepad). Fortunately, it seems like there is no need for it.

**Comment by lieve-blendi** [comment]
Just tested again and, yes, pressing a button before rumbling fixes the issue on my end aswell, however it is a bit weird that I don't have to press a button on my switch controller, but I do on my xbox controller.

**Comment by kmamal** [comment]
Following the advice in [this thread](https://github.com/libsdl-org/SDL/issues/5502) I have added `SDL_SetHint(SDL_HINT_JOYSTICK_RAWINPUT, "0");` to the SDL init code. This is now part of `v0.7.7`. Let me know if it's working better. I don't currenty have a device I can use to test this so I depend on your input. If this still doesn't work then I'm afraid you will have to add a message in your application to "please press a button on your controller" until I can find some other fix.

**Comment by QwertyR0** [comment]
> Following the advice in [this thread](https://github.com/libsdl-org/SDL/issues/5502) I have added `SDL_SetHint(SDL_HINT_JOYSTICK_RAWINPUT, "0");` to the SDL init code. This is now part of `v0.7.7`. Let me know if it's working better. I don't currenty have a device I can use to test this so I depend on your input. If this still doesn't work then I'm afraid you will have to add a message in your application to "please press a button on your controller" until I can find some other fix.

Hello again, Unfortunately it doesn't seem to work for me. Should I keep this issue open? But, still, thanks for your work!

**Comment by lieve-blendi** [comment]
I did some testing and, for me, it still seems to have the same behavior as before (button press required on my xbox controller, no button press required on switch controller)

**Comment by kmamal** [comment]
Thanks guys, yes plese keep the issue open so others can find it easier. I'll try to get my hands on a device so I can test this myself.

**Comment by kmamal** [comment]
This should be fixed in `v0.7.8`. I was able to reproduce the problem using an emulated xbox 360 controller in windows and it is fixed for me.

**Comment by QwertyR0** [comment]
Hello again, Unfortunately it didn't work for me, I still have to press a button for it to rumble. It should be a problem on my side. Thanks for your work.

**Comment by kmamal** [comment]
Is it still saying "Controller isn't correlated yet, try hitting a button first"?

**Comment by QwertyR0** [comment]
Yes it is. Both with Joystick and Controller instances.

**Comment by QwertyR0** [comment]
So, I tested around with these online gamepad testers. It turns out that in different modes of my gamepad, I don't actually need to click any buttons to make it detected. But the problem is that the other modes, except the Xbox 360 one, don't have rumbling enabled. You mentioned that v0.7.8 solved the issue for you, so the correlating problem has something to do with my gamepad. I am closing this issue. Thank you for your work!
