### ISSUE TITLE
macOS Metal backend support

### ISSUE THREAD

**Issue by ExProbitasFiducia** [kmamal/node-sdl#37]
I think sdl2 supports metal. 

Its supported in other SDL2 bindings eg for Julia: https://github.com/JuliaMultimedia/SimpleDirectMediaLayer.jl/blob/bf7ec1bad5839f6e5b15f2e5aed09ee94a093939/src/LibSDL2.jl#L1948

It looks like node-sdl doesn't support this window mode.

**Comment by kmamal** [comment]
@ExProbitasFiducia For using APIs like Metal, Vulkan, and DirectX12 I think it's a better idea to use the WebGPU APIs: https://www.npmjs.com/package/@kmamal/gpu. WebGPU will automatically use Metal, Vulkan, or DirectX12 under the hood, depending on if you are on Mac, Linux, or Windows, and you don't have to write custom code for each platform. As a bonus point the same code will also work in a web browser.

I could of course add an option to use the metal backend to node_sdl, but then you would also need bindings for the metal api functions. Do you have such bindings? I can't find any relevant packages on npm. Are you planning on implementing them yourself?
