### ISSUE TITLE
Permit high pixel density windows

### ISSUE THREAD

**Issue by jweissman** [kmamal/node-sdl#39]
### Background
It would be valuable to be able to draw sharp images and graphics on high-density screens.

### Discussion
We could pass an additional flag (`SDL_WINDOW_ALLOW_HIGHDPI`) here to provide the high DPI option:

https://github.com/kmamal/node-sdl/blob/35a61a985b7e030edea32576de0ac4a201c759bb/src/native/sdl-helpers.cpp#L1407

We will need a way to determine "drawable size" also as per this SO discussion -- https://stackoverflow.com/questions/34842643/how-to-get-the-physical-display-resolution-in-sdl2. This could amount to exposing `SDL_GL_GetDrawableSize` via the window somehow although a bit less clear to me.

**Comment by kmamal** [comment]
Sorry for responding late. I'm currently in the process of switching jobs. I'll have a go at this soon.

**Comment by kmamal** [comment]
@jweissman I tried adding this in `v0.8.0`. You should now always get the width and height for drawing using the `pixelWidth` and `pixelHeight` properties. I have also updated the examples accordingly. I don't currently have access to a high-dpi display so let me know if it worked.
