### ISSUE TITLE
How to deal with text?

### ISSUE THREAD

**Issue by joepie91** [kmamal/node-sdl#40]
When drawing stuff with OpenGL, you would normally use something like FreeType to render text and use that in your rendered output. How should I approach that with this library (or, for that matter, [@kmamal/gl](https://www.npmjs.com/package/@kmamal/gl) directly), given that we're not working in C here? What would the most practical integration point be? As I couldn't find any text-related APIs within this library.

**Comment by joepie91** [comment]
Ah, well, I'm not using FreeType in any particular way yet - as I wasn't sure what the most effective (and especially performant) approach would be here :)

I assume that combining the `canvas` approach with OpenGL would take the form of just using the `canvas` target buffer as an OpenGL texture, or something along those lines?

**Comment by kmamal** [comment]
> I assume that combining the canvas approach with OpenGL would take the form of just using the canvas target buffer as an OpenGL texture, or something along those lines?

Yeah, that's what I was thinking. It's the simplest method I'm aware of. If you plan to use text for gui elements only then you can pre-render all the canvas buffers. If you use a fixed-width font you only have to make a single texture containing all characters and render text using uv coordinates. Performance should be excellent for both these cases.
