### ISSUE TITLE
Feature Req: Motion Controls? Gyro/ Accelerometer?

### ISSUE THREAD

**Issue by HilariousCow** [kmamal/node-sdl#42]
Great to see that this project exists! I ddin't see where I might grab motion data from the IMU. Any plans for reading gyro for the sake of dualshock, dualsense, ninendo switch pro/joycons?

**Comment by kmamal** [comment]
Sure thing. I would have to integrate the sensors API for that. I don't really have any devices I can test this with but maybe you can help me out with testing. I'll let you know when it's done.

**Comment by kmamal** [comment]
@HilariousCow I have added this in `v0.8.4`. I believe the sensors on your controller should appear under `sdl.sensor.devices`. Let me know if it works.

**Comment by HilariousCow** [comment]
I hope to try tomorrow or at the weekend! Thank you so much for taking the time!
