### ISSUE TITLE
Type definition error

### ISSUE THREAD

**Issue by C0deBr3ak3r** [kmamal/node-sdl#44]
Hi, I was doing some tests with the library and it was doing great, however for some reason when using tsc to transpile my project this error about the type definition is raised:
```
node_modules/@kmamal/sdl/src/types/index.d.ts:1190:1 - error TS2309: An export assignment cannot be used in a module with other exported elements.

1190 export = sdl
     ~~~~~~~~~~~~


Found 1 error in node_modules/@kmamal/sdl/src/types/index.d.ts:1190
```
It doesn't seem to affect in the transpiling tho, is still working without any issues AFAIK, is more of an annoyance than anything else.
I'm just starting with TS so I really don't understand what is happening

**Comment by kmamal** [comment]
Thanks for reporting. I have noticed the error before. There was some reason I ended up using `export = sdl` but I don't remember exactly why. I'll try to investigate.

**Comment by kienhg96** [comment]
Hi, I am facing the same problem.

`There are types at '.../node_modules/@kmamal/sdl/src/types/index.d.ts', but this result could not be resolved when respecting package.json "exports". The '@kmamal/sdl' library may need to update its package.json or typings.`

After removing `"exports": "./src/javascript/index.js",`, all the errors are gone

**Comment by kmamal** [comment]
@C0deBr3ak3r Try with the latest version.

@kienhg96 That looks like a different error. Try with the latest version. If that doesn't help share your `tsconfig.json` and typescript version.

**Comment by kienhg96** [comment]
@kmamal, I upgraded to 0.9.3, but the error's still there.
This is my tsconfig.json:
`{
  "compilerOptions": {
    "target": "ESNext",
    "module": "NodeNext",
    "moduleResolution": "NodeNext",
    "allowJs": true,
    "checkJs": true,
    "outDir": "./dist",
    "esModuleInterop": true,
    "forceConsistentCasingInFileNames": true,
    "strict": true,
    "skipLibCheck": true
  },
  "exclude": ["node_modules"],
  "include": ["lib", "demo"]
}`

**Comment by C0deBr3ak3r** [comment]
@kmamal the new version fixed it, thanks

**Comment by kmamal** [comment]
@kienhg96 Try version 0.9.4

**Comment by kienhg96** [comment]
@kmamal It works
