### ISSUE TITLE
how to package this into an executable

### ISSUE THREAD

**Issue by mreinstein** [kmamal/node-sdl#46]
I'm trying to package this up into an `.exe` for windows. I've tried https://www.npmjs.com/package/pkg but I get some errors.  I'm wondering if there's a known/suggested way to bundle this up so that I can distribute it to testers without them needing to install nodejs.

**Comment by kmamal** [comment]
@mreinstein In the past when I've wanted to distribute something up I used https://github.com/kmamal/packager. It creates a simple zip file which contains the nodejs executable inside, the entire source code and node_modules folder, and a script to run everything. It has not seen action in quite some while though and I don't know what state the code is in. Let me know if you plan to use it.

I have thought about how I would create an actual .exe from a nodejs project but it's a lot of work. Especially if you also want to support code signing. It's a shame pkg got deprecated. What errors are you getting? Have you tried any of the forks?

Node.js recently added [Single Executable Applications](https://nodejs.org/api/single-executable-applications.html) but they can only be used for single scripts, so no loading of native modules.

**Comment by mreinstein** [comment]
Thanks for the heads-up!  `kmamal/packager` looks like it could _maybe_ be viable for at least enabling testers, but ideally there would be some way to obfuscate the code so as to hide it.  I might give that a try and see if it enables testing my current app prototype at least.

> I have thought about how I would create an actual .exe from a nodejs project but it's a lot of work.

Bummer.  Makes sense though.  I could use electron, although my app is using UDP which the browser lacks any API for, so I'd need to build a websocket <-> udp bridge.  Probably much easier than re-factoring everything to work in SDL and figuring out a workable, production-ready packaging method though.

>  What errors are you getting? Have you tried any of the forks?

I haven't tried any forks, didn't know there were any viable ones.  Here are the errors I'm getting in trying to use `pkg` on the bare-bones canvas + sdl demo from your repo:
Here's what I'm seeing (out.js is the bundled code):
```bash
➜ pkg out.js --targets latest-macos-x64 -o Weeee

> pkg@5.8.1
> Warning Babel parse has failed: 'await' is only allowed within async functions and at the top levels of modules. (2724:14)
> Warning Failed to make bytecode latest-x64 for file /snapshot/test-sdl/out.js
```

 I did briefly look at node's SEA stuff, though I didn't see any way to load native modules _or_ bundle assets like images/sounds/etc.

**Comment by kmamal** [comment]
I'll have another look around for potential solutions.

**Comment by mreinstein** [comment]
Thanks!  Please don't feel like you need to burn much/any time on this, I can workaround the current situation as needed.

**Comment by kmamal** [comment]
@mreinstein I figured out something and wrote up an example here: https://github.com/kmamal/node-sdl/tree/master/examples/16-pkg

* I'm using the [@yao-pkg/pkg](https://www.npmjs.com/package/@yao-pkg/pkg) package which is a fork of the original [vercel/pkg](https://github.com/vercel/pkg) one.
* ES modules are not yet supported by `pkg` so we have to use the old CommonJS modules (`require` instead of `import`).
* SDL is dynamically linked, so you need to distribute the library files along with the executable, side by side.
* Because we are depending on native modules, each platform's binary has to be built on that platform.

I got the example to run on Linux and Windows. Let me know if you encourter any difficulties.

**Comment by mreinstein** [comment]
I figured out something and wrote up an example here>

That's amazing, thank you for this!

> ES modules are not yet supported by pkg

Gah.  I  wish node and it's ecosystem would catch up already.  My whole app is using esm throughout.  I guess this can be worked around by bundling into a single file before `pkg`ing?

**Comment by notchris** [comment]
Not sure if this is helpful, but another library, NodeGUI that is built around QT and it also has a packager. Wondering how they do it (maybe they hook into QTs packager?) https://github.com/nodegui/packer

**Comment by kmamal** [comment]
> I guess this can be worked around by bundling into a single file before `pkg`ing?

I wrote up [another example](https://github.com/kmamal/node-sdl/tree/master/examples/17-pkg-webpack) using ES modules and Webpack to bundle them to a `node` target. I'm outputing the bundle to the `build` folder which becomes essentially a new commonjs package, with its own `package.json`, that I then pass to `pkg`. Setting up a bundling/transpiling step is always a pain. Hope this helps you set up your own.

**Comment by mreinstein** [comment]
Works great!

<img width="595" alt="Screenshot 2024-02-07 at 10 40 01 PM" src="https://github.com/kmamal/node-sdl/assets/718067/2bdd8d49-ef01-4321-9ffb-926ca342f317">
