### ISSUE TITLE
Error: SDL_GetDisplayDPI(0) error: Couldn't get DPI

### ISSUE THREAD

**Issue by icejix** [kmamal/node-sdl#48]
I'm getting an error in src/javascript/video/index.js (line 6) when the displays are fetched, and it's seemingly (by the error I'm getting) unable to get my DPI. I'm on a device which is very niche, and there are likely some issues between the display drivers and this software.

I have created a temporary solution, which should make this library run on my device, at least. I don't know C++, so I cannot help with that part. You may ignore my fork if you have a different solution to the problem in the C++ half.

https://github.com/icejix/node-sdl-fix

Stack trace:

- src/javascript/video/index.js:6:29
- [node.js internals for 6 lines]
- src/javascript/index.js:8:19
- [node.js internals for 2 lines]

The origin problem seems like an issue in the C++ code to me.

**Comment by icejix** [comment]
Forgot to mention, I've used this library on a few other devices, and none of them encounter this issue. It's probably the device I'm using. Either way, no other applications encounter a problem like this, so I assume there's a bug in node-sdl and not in my system.

**Comment by kmamal** [comment]
Thanks for reporting! You're right, I wasn't handling the error condition of `SDL_GetDisplayDPI` correctly. I tried fixing this in `v0.10.6`. Let me know if it works for you now.

**Comment by icejix** [comment]
> @icejix Thanks for reporting! You're right, I wasn't handling the error condition of `SDL_GetDisplayDPI` correctly. I tried fixing this in `v0.10.6`. Let me know if it works for you now.

That's good to hear! I'll check on it when I get a chance.
