### ISSUE TITLE
Add TypeScript support to @kmamal/gl

### ISSUE THREAD

**Issue by LmanTW** [kmamal/node-sdl#49]
It seems like @kmamal/gl doesn't support TypeScript yet. it'll be really nice if we have type declaration, thx!

**Comment by kmamal** [comment]
@LmanTW I tried adding types in `8.0.2-0`. Let me know if it works.

**Comment by LmanTW** [comment]
There seems to be some problem with `WebGLContextAttributes`.

```ts
const window = sdl.video.createWindow({ opengl: true })
const ctx = createContext(window.pixelWidth, window.pixelHeight, { window: window.native })
//                                                               ^ Object literal may only specify known properties, and 'window' does not exist in type 'WebGLContextAttributes'.
```

**Comment by kmamal** [comment]
@LmanTW Damn missed that one, try with `v8.0.2-2`.

**Comment by kmamal** [comment]
Actually gimem a minute, I just setup typescript and I'll try it out myself.

**Comment by kmamal** [comment]
@LmanTW With `v8.0.2-5` it works for me.

**Comment by LmanTW** [comment]
Yep, it works fluently, thx!
