### ISSUE TITLE
will node-sdl add bindings for the timer functions?

### ISSUE THREAD

**Issue by mreinstein** [kmamal/node-sdl#5]
SPECTRE mitigations have really neutered high performance timers in v8/node.  It could be really great to have access to the high precision timer related calls from sdl, like `SDL_GetTicks64`, `SDL_GetPerformanceCounter`, etc.

**Comment by kmamal** [comment]
@mreinstein AFAIK the spectre mitigations in v8 don't apply to nodejs timers, which are based on libuv. Have you noticed a degradation when using `process.hrtime.bigint()`?

**Comment by mreinstein** [comment]
Ahh I hadn't considered `process.hrtime` good point!

I was considering only v8's `performance.now()` which was originally a high resolution timer  but has had jitter and lower resolution intentionally added.

I guess maybe there's a question of API ergonomics related to working with a bigint vs having things expressed in ticks (SDL's functions are relative to the start of SDL and are smaller values) but that's minor; at least I know of a way to get high precision time for my simulation dt.

thanks for your time! ❤️
