### ISSUE TITLE
Listening to all the events on a window does not work as expected

### ISSUE THREAD

**Issue by LmanTW** [kmamal/node-sdl#51]
When listening to all the events on a window, the callback value is just a `<string>` instead of an `<Events.Window.Any>`.
```ts
const window = sdl.video.createWindow()

window.on('*', (event) => console.log(event))
```

**Comment by kmamal** [comment]
This should be fixed in the latest version. I had the type definition wrong: when you listen to all events the first argument is the event type, and the second is the event. Thy this code instead: `window.on('*', console.log)`.

**Comment by LmanTW** [comment]
Cool, thx!
