### ISSUE TITLE
How to use the Event in window?

### ISSUE THREAD

**Issue by Lman-TW** [kmamal/node-sdl#7]
Hi I am making a simple game engine

I don't understand the Event using Window because it doesn't seem to have those functions in it

(And then this thing is really awesome)

**Comment by kmamal** [comment]
@Lman-TW the window class is a normal Node.js [EventEmitter](https://nodejs.org/api/events.html) so you can handle events with code such as `win.on('event-name', () => { ... callback ... })`.

For example, to print print the size of the window to the console whenever it is resized you would add code like:
```
const window = sdl.video.createWindow()
window.on('resize', console.log)
```

Check the [examples](https://github.com/kmamal/node-sdl/tree/master/examples) to get an idea of how to use this library.

**Comment by Lman-TW** [comment]
OK, thanks for your help!
