### ISSUE TITLE
Play Audio File

### ISSUE THREAD

**Issue by Lman-TW** [kmamal/node-sdl#8]
Hi, here I am again
I would like to ask how to play audio files (like wav, mp3) because I don't see any example like this

(These things are a bit complicated for me, sorry LoL)

**Comment by kmamal** [comment]
@Lman-TW I have added an example of loading an audio file: https://github.com/kmamal/node-sdl/tree/master/examples/11-ffmpeg-audio

I prefer using FFmpeg for anything media encoding/decoding related, but nothing's stopping you from using something simpler. There are a lot of libraries on npm for decoding wav and mp3 files to get the PCM data as a buffer. The only thing you have to be careful with is that the channels, frequency, and format of your data matches that of the audio instance you using.

**Comment by Lman-TW** [comment]
ok, thanks for your help!
